spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

potner:
  mqtt:
    broker-url: ${MQTT_BROKER_URL:tcp://mosquitto:1883}
    client-id: ${MQTT_CLIENT_ID:potner-backend-prod}
